services:
  postgres:
    image: postgres:17
    container_name: ftransfer_postgres_dev
    environment:
      POSTGRES_USER: user
      PGUSER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: ftransfer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  sftp1:
    image: atmoz/sftp:latest
    container_name: ftransfer_sftp1_dev
    ports:
      - '2221:22'
    command: user1:pass1:1001:100:/home/user1/upload

  sftp2:
    image: atmoz/sftp:latest
    container_name: ftransfer_sftp2_dev
    ports:
      - '2222:22'
    command: user2:pass2:1002:100:/home/user2/upload

volumes:
  postgres_data_dev: