services:
  postgres:
    image: postgres:17
    container_name: ftransfer_postgres_dev
    environment:
      POSTGRES_USER: user
      PGUSER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: ftransfer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  postgres_data_dev: